# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to S3

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  push:
    branches: [ test-gihan ]
  pull_request:
    branches: [ test-gihan ]

env:
  REACT_APP_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
  REACT_APP_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
  REACT_APP_REGION: ${{ secrets.REACT_APP_REGION }}

  REACT_APP_USER_POOL_ID: ${{ secrets.REACT_APP_USER_POOL_ID }}
  REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
  REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }} 

  REACT_APP_UPLOAD_URL: ${{ secrets.REACT_APP_UPLOAD_URL }}
  REACT_APP_CARD_URL: ${{ secrets.REACT_APP_CARD_URL }}
  REACT_APP_CAMPAIGN_URL: ${{ secrets.REACT_APP_CAMPAIGN_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js and NPM
      uses: actions/setup-node@v1
      with: 
        node-version: '16.x'          

    - name: Build React app
      run: npm install && npm run build

    - name: Test React app
      run: npm run test

    - name: Upload to S3
      run: aws s3 sync ./build/ s3://project-2022-23t2-g1-team3-s3 --delete
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
        AWS-REGION: ${{ secrets.REACT_APP_REGION }}



